################################
# INFO: Keep this file as it is for testing purposes
#       Any new config files should be copied and not rewrite this file
################################
# 
# General part
#
# ############################

url: "https://localhost/test"
tokenuser: "test"
tokenpass: "test"

###############################
#
# Sensors
#
# Parts where you can enable disable specific sensors
# Possible options:
#  - humidity - read the DHT11 humidity sensors content
#  - temperature - read the DHT11 temperature sensor
###############################

sensors:
    - humidity
    - temperature
